### ISSUE TITLE
Request to update description of rust-nomicon-ja

### ISSUE THREAD

**Issue by imsut** [rust-lang-ja/rust-nomicon-ja#3]
@chikoski @KeenS @tatsuya6502 さん

リポジトリを移行した際に、project description に古いリンクが残ってしまいました。
この部分は owner しか変更できないようなので、時間があるときに、
スクリーンショットの赤枠の部分を削除していただけるでしょうか?

![project-description](https://cloud.githubusercontent.com/assets/65684/25017852/0e405f46-203a-11e7-8955-360d870706ff.png)

**Comment by KeenS** [comment]
変更しておきました。ついでにimsutさんをこのレポジトリのadminにしておきましたのでもしかしたら今後は自分で管理出来るかもしれません。

**Comment by imsut** [comment]
ありがとうございます！
